### ISSUE TITLE
IEnumerable collection properties

### ISSUE THREAD

**Issue by fjmorel** [acolom/ToStringSourceGenerator#1]
Hi,

Do you have any plans to work on this library further? This is really close to what I'm looking for, missing just what's in the "Next Changes" section.

This would be really useful in writing tests. Currently we use https://github.com/diegofrata/Generator.Equals to generate better `Equals/GetHashCode` implementations so we can compare objects with collections in them. I would love a better `ToString` so that the test output has more useful information when the contents of a collection property are not the same.

**Comment by acolom** [comment]
Hello,

Thanks for contacting, I started this project as a side project and i'm not currently working on it. Unfortunately nowadays i have not the time to improve it.

Good luck!
